"Name: \FU:SD_SHIPMENT_STATUS_COMPLETION\SE:END\EI
ENHANCEMENT 0 Z_DETERMINA_DATA_HORA.
*
  CALL FUNCTION 'Z_LES_AJUSTA_DATA_HORA'
    EXPORTING
      I_ERNAM       = C_XVTTK_WA-ERNAM
    CHANGING
      I_DATA        = c_xvttk_wa-dtabf
      I_HORA        = c_xvttk_wa-uzabf.

ENDENHANCEMENT.
