*"* use this source file for your ABAP unit test classes
CLASS LTCL_MEW_DOC_CTB DEFINITION FINAL FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS.

  PRIVATE SECTION.
    METHODS:
      FIRST_TEST FOR TESTING RAISING CX_STATIC_CHECK.
ENDCLASS.


CLASS LTCL_MEW_DOC_CTB IMPLEMENTATION.

  METHOD FIRST_TEST.

    DATA: I_INFO    TYPE ZDE_INTEGRACAO_HTTP_CONFIG,
          I_ENTRADA TYPE ZDE_NEW_DOC_CTB,
          I_ITEM    TYPE ZDE_NEW_DOC_CTB_ITM.

    I_ENTRADA-CH_REFERENCIA = 'ZG999993199382021'.
    I_ENTRADA-TX_CABECALHO  = 'Gestão Emissão NF'.
    I_ENTRADA-CD_EMPRESA    = '0001'.
    I_ENTRADA-DT_DOCUMENTO  = '13.03.2020'.
    I_ENTRADA-DT_LANCAMENTO = '13.03.2020'.
    I_ENTRADA-TP_DOCUMENTO  = 'WR'.
    I_ENTRADA-NU_DOC_REFERENCIA = 'GF0000319938'.
    I_ENTRADA-ID_INTERFACE = '03'.

    CLEAR: I_ITEM.
    I_ITEM-CH_LANCAMENTO = '40'.
    I_ITEM-CN_CLIENTE_FORNECEDOR = '0000213000'.
    I_ITEM-VR_ITEM = '65652.83'.
    I_ITEM-CD_MOEDA = 'BRL'.
    I_ITEM-CD_FILIAL = '0185'.
    I_ITEM-DIVISAO = '0185'.
    I_ITEM-SQ_ITEM = '000001'.
    APPEND I_ITEM TO I_ENTRADA-ITENS.

    CLEAR: I_ITEM.
    I_ITEM-CH_LANCAMENTO = '50'.
    I_ITEM-CN_CLIENTE_FORNECEDOR = '0000213000'.
    I_ITEM-VR_ITEM = '65652.83'.
    I_ITEM-CD_MOEDA = 'BRL'.
    I_ITEM-CD_FILIAL = '0101'.
    I_ITEM-DIVISAO = '0101'.
    I_ITEM-SQ_ITEM = '000002'.
    APPEND I_ITEM TO I_ENTRADA-ITENS.

    DATA(JSON_STRING) =  ZCL_FMCALL_BASE=>ABAP2JSON( EXPORTING ABAP_DATA = I_ENTRADA ).

    I_INFO-DS_BODY = JSON_STRING.
    I_INFO-DS_CONTENT_TYPE = ''.
    I_INFO-DS_FORMATO = ''.
    I_INFO-DS_IP_ORIGEM = SY-HOST.
    I_INFO-DS_METODO = 'POST'.
    I_INFO-DS_SERVER_PROTOCOLO = 'HTTP'.
    I_INFO-DS_URL = 'http://localhost/'.

    ZCL_INTEGRACAO_NEW_DOC_CTB=>ZIF_INTEGRACAO_NEW_DOC_CTB~GET_INSTANCE(
       )->SET_DS_DATA( I_INFO = I_INFO
       )->SET_SEND_MSG( IMPORTING E_PROTOCOLO = DATA(E_PROTOCOLO) E_MSG = DATA(O_CDATA)
       ).

    CL_ABAP_UNIT_ASSERT=>ASSERT_DIFFERS( EXPORTING ACT = E_PROTOCOLO EXP = '000000000000000' ).

    SELECT SINGLE * INTO @DATA(WA_ZFIT0158)
      FROM ZFIT0158
     WHERE OBJ_KEY EQ @I_ENTRADA-CH_REFERENCIA.

    CL_ABAP_UNIT_ASSERT=>ASSERT_EQUALS( EXPORTING ACT = E_PROTOCOLO EXP = WA_ZFIT0158-PROTOCOLO ).

    SELECT * INTO TABLE @DATA(IT_ZIB_CONTABIL)
      FROM ZIB_CONTABIL
     WHERE OBJ_KEY EQ @I_ENTRADA-CH_REFERENCIA.

    CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL( EXPORTING ACT = IT_ZIB_CONTABIL ).

    DESCRIBE TABLE IT_ZIB_CONTABIL LINES DATA(QT_LINHAS).

    CL_ABAP_UNIT_ASSERT=>ASSERT_EQUALS( EXPORTING ACT = QT_LINHAS EXP = 2 ).

    SELECT * INTO TABLE @DATA(IT_ZIB_CONTABIL_ERR)
      FROM ZIB_CONTABIL_ERR
     WHERE OBJ_KEY EQ @I_ENTRADA-CH_REFERENCIA.

    CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL( EXPORTING ACT = IT_ZIB_CONTABIL_ERR ).

  ENDMETHOD.

ENDCLASS.
