
CLASS ZCL_CARGA_RECEBIMENTO_TESTE DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
.
*?﻿<asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
*?<asx:values>
*?<TESTCLASS_OPTIONS>
*?<TEST_CLASS>zcl_Carga_Recebimento_Teste
*?</TEST_CLASS>
*?<TEST_MEMBER>f_Cut
*?</TEST_MEMBER>
*?<OBJECT_UNDER_TEST>ZCL_CARGA_RECEBIMENTO
*?</OBJECT_UNDER_TEST>
*?<OBJECT_IS_LOCAL/>
*?<GENERATE_FIXTURE/>
*?<GENERATE_CLASS_FIXTURE/>
*?<GENERATE_INVOCATION/>
*?<GENERATE_ASSERT_EQUAL/>
*?</TESTCLASS_OPTIONS>
*?</asx:values>
*?</asx:abap>
  PRIVATE SECTION.
    DATA:
      F_CUT TYPE REF TO ZCL_CARGA_RECEBIMENTO.  "class under test

    METHODS: ADD_NOTA_FISCAL FOR TESTING.
    METHODS: ADD_ORDEM_VENDA FOR TESTING.
    METHODS: BLOQUEAR_ENTRADA FOR TESTING.
    METHODS: DESBLOQUEAR_ENTRADA FOR TESTING.
    METHODS: EXCLUIR_NOTA_FISCAL FOR TESTING.
    METHODS: EXCLUIR_REGISTRO FOR TESTING.
    METHODS: FREE FOR TESTING.
    METHODS: GERAR_CARGA_SAIDA FOR TESTING.
    METHODS: GERA_ERRO_GERAL FOR TESTING.
    METHODS: GET_CABECALHO_CARGA FOR TESTING.
    METHODS: GET_CALCULAR_SUBTOTAL FOR TESTING.
    METHODS: GET_CHECK_JOB_EXECUCAO FOR TESTING.
    METHODS: GET_CHECK_JOB_EXECUCAO_ESTORNO FOR TESTING.
    METHODS: GET_CK_CARGA_SEM_SOLIC_MANUT FOR TESTING.
    METHODS: GET_CK_DOC_TRANSPORTE_EXISTE FOR TESTING.
    METHODS: GET_CK_EXCLUIR_ROMANEIO_SAIDA FOR TESTING.
    METHODS: GET_CK_GERA_SOBRA FOR TESTING.
    METHODS: GET_CK_SAIDA_AUTOMATICA FOR TESTING.
    METHODS: GET_CK_SOL_AJUSTE_NAO_PROC FOR TESTING.
    METHODS: GET_CK_SUB_CARAC_AVA_MATERIAL FOR TESTING.
    METHODS: GET_DOCUMENTO_ENT_ESTORNADO FOR TESTING.
    METHODS: GET_FACTORY_TP_TRANSGENIA FOR TESTING.
    METHODS: GET_INFO_ALV_APRESENTACAO FOR TESTING.
    METHODS: GET_INFO_ALV_APRESENTACAO_LOG FOR TESTING.
    METHODS: GET_INFO_MESSAGEM_ESTORNO FOR TESTING.
    METHODS: GET_INFO_ORDEM_VENDA FOR TESTING.
    METHODS: GET_INFO_PEDIDO_COMPRA FOR TESTING.
    METHODS: GET_INFO_PLACA FOR TESTING.
    METHODS: GET_INSTANCE FOR TESTING.
    METHODS: GET_LOGS_HISTORICO FOR TESTING.
    METHODS: GET_MENS_INTERFACE_ENTRADA FOR TESTING.
    METHODS: GET_NAME_JOB_SAIDA_AUTOMATICA FOR TESTING.
    METHODS: GET_NEW_ID_CARGA FOR TESTING.
    METHODS: GET_NEW_ID_CLASSIFICAO FOR TESTING.
    METHODS: GET_NEW_ID_ENTRADA_ESTOQUE FOR TESTING.
    METHODS: GET_NEW_ID_SOLICITACAO_MANUT FOR TESTING.
    METHODS: GET_NOTA_FORNECEDOR_IE FOR TESTING.
    METHODS: GET_PARTINER_ORDEM_VENDA FOR TESTING.
    METHODS: GET_PEDIDO_COMPRA FOR TESTING.
    METHODS: GET_PRODUTOR_FILIAL_SAFRA FOR TESTING.
    METHODS: GET_RATEIA_DESCONTOS FOR TESTING.
    METHODS: GET_RECUPERAR_ENTRADA FOR TESTING.
    METHODS: GET_REGISTRO FOR TESTING.
    METHODS: GET_RESULT_DESC_CLASSIFICACAO FOR TESTING.
    METHODS: GET_ROMANEIO_ENTRADA FOR TESTING.
    METHODS: GET_ROMANEIO_SAIDA FOR TESTING.
    METHODS: GET_TP_STATUS FOR TESTING.
    METHODS: GET_VALIDAR_NOTA_FISCAL FOR TESTING.
    METHODS: GET_VERIFICA_EXISTE_SAIDA FOR TESTING.
    METHODS: GRAVAR_REGISTRO FOR TESTING.
    METHODS: LIMPAR_REGISTRO FOR TESTING.
    METHODS: NOVO_REGISTRO FOR TESTING.
    METHODS: PESQUISAR FOR TESTING.
    METHODS: PESQUISAR_SOLICITACAO_MANUT FOR TESTING.
    METHODS: SEND_CARGA_TO_OPUS FOR TESTING.
    METHODS: SEND_ESTORNO_CARGA_TO_OPUS FOR TESTING.
    METHODS: SET_ABRIR FOR TESTING.
    METHODS: SET_ACEITE_SOLI_MANUTENCAO FOR TESTING.
    METHODS: SET_ADD_BLOCO FOR TESTING.
    METHODS: SET_ADD_FORN_FILIAL_SAFRA FOR TESTING.
    METHODS: SET_ADD_TAKE_UP FOR TESTING.
    METHODS: SET_AGENTE_FRETE FOR TESTING.
    METHODS: SET_AJUSTAR_RAT_DESC_GERAL FOR TESTING.
    METHODS: SET_AJUSTAR_RAT_ORDEM_VENDA FOR TESTING.
    METHODS: SET_BLOQUEAR_ROMANEIOS_SAIDA FOR TESTING.
    METHODS: SET_CANCELAR FOR TESTING.
    METHODS: SET_CANCELAR_SOLIC_MANUT FOR TESTING.
    METHODS: SET_CARGA FOR TESTING.
    METHODS: SET_CONFERIDO FOR TESTING.
    METHODS: SET_CONFERIR_SOLIC_MANUT FOR TESTING.
    METHODS: SET_CRIA_MANUTENCAO FOR TESTING.
    METHODS: SET_DENQUEUE FOR TESTING.
    METHODS: SET_DENQUEUE_ROMANEIO FOR TESTING.
    METHODS: SET_DESBLOQUEAR_ROMANEIOS_SAID FOR TESTING.
    METHODS: SET_EMITIR_DOC_SAIDAS FOR TESTING.
    METHODS: SET_ENQUEUE FOR TESTING.
    METHODS: SET_ENQUEUE_ROMANEIO FOR TESTING.
    METHODS: SET_ESTORNA_FRETE_ENTRADA FOR TESTING.
    METHODS: SET_EXCLUIR_BLOCO FOR TESTING.
    METHODS: SET_EXCLUIR_ORDEM_VENDA FOR TESTING.
    METHODS: SET_EXC_TAKE_UP FOR TESTING.
    METHODS: SET_FECHAR FOR TESTING.
    METHODS: SET_GERAR_ENTRADA_ESTOQUE FOR TESTING.
    METHODS: SET_GERAR_ESTORNO_ESTOQUE FOR TESTING.
    METHODS: SET_GERAR_FATURA FOR TESTING.
    METHODS: SET_GERAR_REMESSAS FOR TESTING.
    METHODS: SET_GERAR_ROMANEIO_ENTRADA FOR TESTING.
    METHODS: SET_GERAR_ROMANEIO_SAIDA FOR TESTING.
    METHODS: SET_GERAR_TRANSPORTE FOR TESTING.
    METHODS: SET_GERA_IMPOSTO_NOTA FOR TESTING.
    METHODS: SET_ID_CARGA FOR TESTING.
    METHODS: SET_ID_CLASSIFICACAO FOR TESTING.
    METHODS: SET_ID_SOLIC_MANUT FOR TESTING.
    METHODS: SET_INFO_FRETE_WITHOUT_OV FOR TESTING.
    METHODS: SET_LIMPA_ROMANEIO_SAIDA FOR TESTING.
    METHODS: SET_LOCAL_ENTREGA FOR TESTING.
    METHODS: SET_LOGS_ALTERACAO FOR TESTING.
    METHODS: SET_NOTA_ENTRADA_PROPRIA FOR TESTING.
    METHODS: SET_OBSERVACAO_NOTA FOR TESTING.
    METHODS: SET_ORDEM_CARREGAMENTO FOR TESTING.
    METHODS: SET_ORDEM_VENDA FOR TESTING.
    METHODS: SET_PESOS_NOTAS FOR TESTING.
    METHODS: SET_PROCESSAR_ENTRADA FOR TESTING.
    METHODS: SET_PROCESSAR_ESTORNO FOR TESTING.
    METHODS: SET_PROCESSAR_ESTORNO_SOBRA FOR TESTING.
    METHODS: SET_PROCESSAR_MANUTENCAO FOR TESTING.
    METHODS: SET_PROCESSAR_SOBRA_FOB FOR TESTING.
    METHODS: SET_REGISTRO FOR TESTING.
    METHODS: SET_REGISTRO_MANUTENCAO FOR TESTING.
    METHODS: SET_TIPO_FRETE_ORDEM_VENDA FOR TESTING.
    METHODS: SET_TRANSGENIA FOR TESTING.
    METHODS: SET_VOLUME_ORDEM_VENDA FOR TESTING.
    METHODS: VALIDAR_EXCLUSAO FOR TESTING.
    METHODS: VALIDAR_REGISTRO FOR TESTING.
    METHODS: VALIDAR_REGISTRO_ORDEM_VENDA FOR TESTING.
    METHODS: VALIDAR_REGISTRO_PEDIDO_COMPRA FOR TESTING.
    METHODS: VALIDA_ATRIBUTO_ALTERAVEL FOR TESTING.
    METHODS: VERIF_ALTERACAO_MANUT_ROMANEIO FOR TESTING.
    METHODS: VERIF_BLOQ_LOTE_MATERIAL_WAIT FOR TESTING.
    METHODS: VERIF_CK_PLUMA_NOTA_FISCAL FOR TESTING.
    METHODS: VERIF_CK_SALDO_TAKEUP_BLOCO FOR TESTING.
    METHODS: VERIF_ESTORNO_PENDENTE FOR TESTING.
    METHODS: VERIF_ORDEM_CARREGAMENTO FOR TESTING.
    METHODS: VERIF_PESO_NOTAS FOR TESTING.
    METHODS: VERIF_SALDO_ORDEM_VENDA FOR TESTING.
    METHODS: VERIF_TICKET_PESAGEM FOR TESTING.
ENDCLASS.       "zcl_Carga_Recebimento_Teste


CLASS ZCL_CARGA_RECEBIMENTO_TESTE IMPLEMENTATION.

  METHOD ADD_NOTA_FISCAL.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD ADD_ORDEM_VENDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD BLOQUEAR_ENTRADA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD DESBLOQUEAR_ENTRADA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD EXCLUIR_NOTA_FISCAL.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD EXCLUIR_REGISTRO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD FREE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GERAR_CARGA_SAIDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GERA_ERRO_GERAL.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CABECALHO_CARGA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CALCULAR_SUBTOTAL.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CHECK_JOB_EXECUCAO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CHECK_JOB_EXECUCAO_ESTORNO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CK_CARGA_SEM_SOLIC_MANUT.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CK_DOC_TRANSPORTE_EXISTE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CK_EXCLUIR_ROMANEIO_SAIDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CK_GERA_SOBRA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CK_SAIDA_AUTOMATICA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CK_SOL_AJUSTE_NAO_PROC.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_CK_SUB_CARAC_AVA_MATERIAL.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_DOCUMENTO_ENT_ESTORNADO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_FACTORY_TP_TRANSGENIA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_INFO_ALV_APRESENTACAO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_INFO_ALV_APRESENTACAO_LOG.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_INFO_MESSAGEM_ESTORNO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_INFO_ORDEM_VENDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_INFO_PEDIDO_COMPRA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_INFO_PLACA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_INSTANCE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_LOGS_HISTORICO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_MENS_INTERFACE_ENTRADA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_NAME_JOB_SAIDA_AUTOMATICA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_NEW_ID_CARGA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_NEW_ID_CLASSIFICAO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_NEW_ID_ENTRADA_ESTOQUE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_NEW_ID_SOLICITACAO_MANUT.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_NOTA_FORNECEDOR_IE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_PARTINER_ORDEM_VENDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_PEDIDO_COMPRA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_PRODUTOR_FILIAL_SAFRA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_RATEIA_DESCONTOS.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_RECUPERAR_ENTRADA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_REGISTRO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_RESULT_DESC_CLASSIFICACAO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_ROMANEIO_ENTRADA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_ROMANEIO_SAIDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_TP_STATUS.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_VALIDAR_NOTA_FISCAL.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GET_VERIFICA_EXISTE_SAIDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD GRAVAR_REGISTRO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD LIMPAR_REGISTRO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD NOVO_REGISTRO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD PESQUISAR.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD PESQUISAR_SOLICITACAO_MANUT.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SEND_CARGA_TO_OPUS.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SEND_ESTORNO_CARGA_TO_OPUS.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_ABRIR.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_ACEITE_SOLI_MANUTENCAO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_ADD_BLOCO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_ADD_FORN_FILIAL_SAFRA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_ADD_TAKE_UP.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_AGENTE_FRETE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_AJUSTAR_RAT_DESC_GERAL.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_AJUSTAR_RAT_ORDEM_VENDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_BLOQUEAR_ROMANEIOS_SAIDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_CANCELAR.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_CANCELAR_SOLIC_MANUT.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_CARGA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_CONFERIDO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_CONFERIR_SOLIC_MANUT.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_CRIA_MANUTENCAO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_DENQUEUE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_DENQUEUE_ROMANEIO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_DESBLOQUEAR_ROMANEIOS_SAID.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_EMITIR_DOC_SAIDAS.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_ENQUEUE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_ENQUEUE_ROMANEIO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_ESTORNA_FRETE_ENTRADA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_EXCLUIR_BLOCO.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_EXCLUIR_ORDEM_VENDA.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_EXC_TAKE_UP.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_FECHAR.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_GERAR_ENTRADA_ESTOQUE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_GERAR_ESTORNO_ESTOQUE.
    CL_AUNIT_ASSERT=>ASSERT_EQUALS( EXPORTING EXP = ''  ACT = '' ).
  ENDMETHOD.


  METHOD SET_GERAR_FATURA.



  ENDMETHOD.


  METHOD SET_GERAR_REMESSAS.



  ENDMETHOD.


  METHOD SET_GERAR_ROMANEIO_ENTRADA.



  ENDMETHOD.


  METHOD SET_GERAR_ROMANEIO_SAIDA.



  ENDMETHOD.


  METHOD SET_GERAR_TRANSPORTE.



  ENDMETHOD.


  METHOD SET_GERA_IMPOSTO_NOTA.



  ENDMETHOD.


  METHOD SET_ID_CARGA.



  ENDMETHOD.


  METHOD SET_ID_CLASSIFICACAO.



  ENDMETHOD.


  METHOD SET_ID_SOLIC_MANUT.



  ENDMETHOD.


  METHOD SET_INFO_FRETE_WITHOUT_OV.



  ENDMETHOD.


  METHOD SET_LIMPA_ROMANEIO_SAIDA.



  ENDMETHOD.


  METHOD SET_LOCAL_ENTREGA.



  ENDMETHOD.


  METHOD SET_LOGS_ALTERACAO.



  ENDMETHOD.


  METHOD SET_NOTA_ENTRADA_PROPRIA.



  ENDMETHOD.


  METHOD SET_OBSERVACAO_NOTA.



  ENDMETHOD.


  METHOD SET_ORDEM_CARREGAMENTO.



  ENDMETHOD.


  METHOD SET_ORDEM_VENDA.



  ENDMETHOD.


  METHOD SET_PESOS_NOTAS.



  ENDMETHOD.


  METHOD SET_PROCESSAR_ENTRADA.



  ENDMETHOD.


  METHOD SET_PROCESSAR_ESTORNO.



  ENDMETHOD.


  METHOD SET_PROCESSAR_ESTORNO_SOBRA.



  ENDMETHOD.


  METHOD SET_PROCESSAR_MANUTENCAO.



  ENDMETHOD.


  METHOD SET_PROCESSAR_SOBRA_FOB.



  ENDMETHOD.


  METHOD SET_REGISTRO.



  ENDMETHOD.


  METHOD SET_REGISTRO_MANUTENCAO.



  ENDMETHOD.


  METHOD SET_TIPO_FRETE_ORDEM_VENDA.



  ENDMETHOD.


  METHOD SET_TRANSGENIA.



  ENDMETHOD.


  METHOD SET_VOLUME_ORDEM_VENDA.



  ENDMETHOD.


  METHOD VALIDAR_EXCLUSAO.



  ENDMETHOD.


  METHOD VALIDAR_REGISTRO.



  ENDMETHOD.


  METHOD VALIDAR_REGISTRO_ORDEM_VENDA.



  ENDMETHOD.


  METHOD VALIDAR_REGISTRO_PEDIDO_COMPRA.



  ENDMETHOD.


  METHOD VALIDA_ATRIBUTO_ALTERAVEL.



  ENDMETHOD.


  METHOD VERIF_ALTERACAO_MANUT_ROMANEIO.



  ENDMETHOD.


  METHOD VERIF_BLOQ_LOTE_MATERIAL_WAIT.



  ENDMETHOD.


  METHOD VERIF_CK_PLUMA_NOTA_FISCAL.



  ENDMETHOD.


  METHOD VERIF_CK_SALDO_TAKEUP_BLOCO.



  ENDMETHOD.


  METHOD VERIF_ESTORNO_PENDENTE.



  ENDMETHOD.


  METHOD VERIF_ORDEM_CARREGAMENTO.



  ENDMETHOD.


  METHOD VERIF_PESO_NOTAS.



  ENDMETHOD.


  METHOD VERIF_SALDO_ORDEM_VENDA.



  ENDMETHOD.


  METHOD VERIF_TICKET_PESAGEM.



  ENDMETHOD.




ENDCLASS.
