*"* use this source file for your ABAP unit test classes
CLASS LTCL_STR DEFINITION FINAL FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS.

  PRIVATE SECTION.
    METHODS:
      MATCH FOR TESTING RAISING CX_STATIC_CHECK,
      MATCH_EMAIL FOR TESTING RAISING CX_STATIC_CHECK,
      LENGTH FOR TESTING RAISING CX_STATIC_CHECK,
      LENGTH_ERRADO FOR TESTING RAISING CX_STATIC_CHECK.

ENDCLASS.


CLASS LTCL_STR IMPLEMENTATION.

  METHOD MATCH.
    CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL( ACT = ZCL_STR=>SET( '9' )->MATCHER( PATTERN = '[0-9]{1}' ) ).
  ENDMETHOD.

  METHOD MATCH_EMAIL.
    CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL( ACT = ZCL_STR=>MATCHER_EMAIL( 'marcus.barbara@hotmail.com' ) ).
  ENDMETHOD.

  METHOD LENGTH.
    CL_ABAP_UNIT_ASSERT=>ASSERT_EQUALS( EXPORTING ACT = ZCL_STR=>SET( 'teste' )->LENGTH( ) EXP = 5 ).
  ENDMETHOD.

  METHOD LENGTH_ERRADO.
    CL_ABAP_UNIT_ASSERT=>ASSERT_DIFFERS( EXPORTING ACT = ZCL_STR=>SET( 'teste_errado' )->LENGTH( ) EXP = 5 ).
  ENDMETHOD.

ENDCLASS.
