class ZCL_INTEGRACAO_MOBILE_EMB definition
  public
  final
  create public .

public section.

  interfaces ZIF_INTEGRACAO_INJECT .
  interfaces ZIF_INTEGRACAO_MOBILE_EMB .

  methods CONSTRUCTOR .
protected section.
private section.
ENDCLASS.



CLASS ZCL_INTEGRACAO_MOBILE_EMB IMPLEMENTATION.


  METHOD CONSTRUCTOR.

    ME->ZIF_INTEGRACAO_INJECT~AT_ID_INTERFACE  = '019'.
    ME->ZIF_INTEGRACAO_INJECT~AT_TP_INTEGRACAO = ZIF_INTEGRACAO=>AT_TP_INTEGRACAO_INBOUND.

    ME->ZIF_INTEGRACAO_INJECT~AT_REFERENCIA-TP_REFERENCIA = 'EMBALAGEM'.
    ME->ZIF_INTEGRACAO_INJECT~AT_TP_CANAL = ZIF_INTEGRACAO=>AT_TP_CANAL_COMUNICA_HTTP.
*    ME->ZIF_INTEGRACAO_INJECT~AT_AUTENTICA_OPUS = ZIF_INTEGRACAO=>AT_ID_INTERFACE_AUT_OPUS_NAO.
*    ME->ZIF_INTEGRACAO_INJECT~AT_SEND_AUTENTICAO = ZIF_INTEGRACAO=>AT_ID_INTERFACE_AUT_SEND_NAO.

  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_INJECT~GET_HEADER_REQUEST_HTTP.

    r_if_integracao_inject = me.
    e_header_fields = me->zif_integracao_inject~at_header_fields.

  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_INJECT~SET_BEFORE_ERROR_OUTBOUND_MSG.

    R_IF_INTEGRACAO_INJECT = ME.
    E_SUCESSO = ABAP_FALSE.

  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_INJECT~SET_BEFORE_SEND_OUTBOUND_MSG.
    r_if_integracao_inject = me.
  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_INJECT~SET_HEADER_REQUEST_HTTP.

    r_if_integracao_inject = me.
    me->zif_integracao_inject~at_header_fields = i_header_fields.

  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_INJECT~SET_INTEGRAR_INBOUND.

    E_SUCESSO = ABAP_TRUE.

    R_IF_INTEGRACAO_INJECT = ME.

  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_INJECT~SET_INTEGRAR_RETORNO.

    "Metodo para Integrar InBound

    R_IF_INTEGRACAO_INJECT = ME.
    E_SUCESSO = ABAP_TRUE.

  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_INJECT~SET_PROCESSA_INBOUND.

    E_SUCESSO = ABAP_TRUE.

    R_IF_INTEGRACAO_INJECT = ME.

  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_INJECT~SET_PROCESSA_RETORNO.

    "Metodo para processoamento de InBound

    R_IF_INTEGRACAO_INJECT = ME.
    E_SUCESSO = ABAP_TRUE.

  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_MOBILE_EMB~GET_INSTANCE.

    IF ZIF_INTEGRACAO_MOBILE_EMB~AT_IF_INTE_MOBILE_EMB IS NOT BOUND.
      CREATE OBJECT ZIF_INTEGRACAO_MOBILE_EMB~AT_IF_INTE_MOBILE_EMB TYPE ZCL_INTEGRACAO_MOBILE_EMB.
    ENDIF.
    R_IF_INTEGRACAO_MOBILE_EMB = ZIF_INTEGRACAO_MOBILE_EMB~AT_IF_INTE_MOBILE_EMB.

  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_MOBILE_EMB~SET_DS_DATA.

    DATA: I_INBOUND TYPE ZPPET015.

    "Incluir Texto JSON para integração
    R_IF_INTEGRACAO_MOBILE_EMB = ME.
    ME->ZIF_INTEGRACAO_INJECT~AT_INFO_REQUEST_HTTP = I_INFO.

    "Validar Json
    /UI2/CL_JSON=>DESERIALIZE( EXPORTING JSON = I_INFO-DS_BODY CHANGING DATA = I_INBOUND ).
    IF I_INBOUND IS NOT INITIAL.
      ME->ZIF_INTEGRACAO_INJECT~AT_REFERENCIA-ID_REFERENCIA = I_INBOUND-EMBALAGENS-PRODUTOS[ 1 ]-ID_MOVIMENTACAO.
    ENDIF.

    CHECK I_INBOUND IS INITIAL.

    RAISE EXCEPTION TYPE ZCX_INTEGRACAO
      EXPORTING
        TEXTID = VALUE #( MSGID = ZCX_INTEGRACAO=>ZCX_ERRO_BODY_RECEBIDO-MSGID
                          MSGNO = ZCX_INTEGRACAO=>ZCX_ERRO_BODY_RECEBIDO-MSGNO )
        MSGID  = ZCX_INTEGRACAO=>ZCX_ERRO_BODY_RECEBIDO-MSGID
        MSGNO  = ZCX_INTEGRACAO=>ZCX_ERRO_BODY_RECEBIDO-MSGNO
        MSGTY  = 'E'.


  ENDMETHOD.


  METHOD ZIF_INTEGRACAO_MOBILE_EMB~SET_SEND_MSG.


    DATA: I_INBOUND TYPE ZPPET015.
    DATA: LC_INTEGRACAO TYPE REF TO ZCL_INTEGRACAO.

    R_IF_INTEGRACAO_MOBILE_EMB = ME.

    /UI2/CL_JSON=>DESERIALIZE( EXPORTING JSON = ME->ZIF_INTEGRACAO_INJECT~AT_INFO_REQUEST_HTTP-DS_BODY CHANGING DATA = I_INBOUND ).

    ME->ZIF_INTEGRACAO_INJECT~AT_INFO_REQUEST_HTTP-DS_FUNCAO_PROCESSA =
    COND #( WHEN I_INBOUND IS NOT INITIAL THEN I_INBOUND-EMBALAGENS-ACAO ELSE '/Embalagem' ).

    CREATE OBJECT LC_INTEGRACAO.

    LC_INTEGRACAO->ZIF_INTEGRACAO~SET_MSG_INJECT( I_MSG = CAST #( ME )
      )->SET_NEW_MSG( IMPORTING E_ID_INTEGRACAO = ME->ZIF_INTEGRACAO_MOBILE_EMB~AT_ID_INTEGRACAO
      )->SET_PROCESSAR_RETORNO(
      )->SET_INTEGRAR_RETORNO(
           IMPORTING
             E_DATA_RETORNO =  DATA(E_DATA_RETORNO)
             E_ZINTEGRACAO_LOG = E_ZINTEGRACAO_LOG
      )->GET_REGISTRO( IMPORTING E_INTEGRACAO = DATA(E_INTEGRACAO)
      )->FREE(
      ).

    E_MSG = E_DATA_RETORNO.
    E_PROTOCOLO = ZCL_STRING=>LPAD( I_STR  = CONV #( E_INTEGRACAO-ID_INTEGRACAO ) I_QTD  = 15 I_CHAR = '0'  ).

    CLEAR: LC_INTEGRACAO.

  ENDMETHOD.
ENDCLASS.
