FUNCTION ZENQUEUE_INTEGRACAO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(ID_INTEGRACAO) TYPE  ZDE_ID_INTEGRACAO
*"     REFERENCE(_SCOPE) DEFAULT '2'
*"     REFERENCE(_WAIT) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT SPACE
*"  EXCEPTIONS
*"      FOREIGN_LOCK
*"      SYSTEM_FAILURE
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __WAIT      TYPE DDENQWAIT.

  __WAIT = _WAIT.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_ZINTEGRACAO,
          MANDT    TYPE SY-MANDT,
          ID_INTEGRACAO TYPE ZDE_ID_INTEGRACAO,
        END OF %A_ZINTEGRACAO.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_ZINTEGRACAO.

  MOVE: ID_INTEGRACAO TO %A_ZINTEGRACAO-ID_INTEGRACAO.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_ZINTEGRACAO-MANDT.
  ENDIF.

* Preencher tab.bloqueio:
  __SEQTA_TAB-GNAME = 'ZINTEGRACAO'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG = %A_ZINTEGRACAO.
  APPEND __SEQTA_TAB.

* Fixar bloqueio:
  PERFORM SEND_ENQUEUE(SAPLSENA)
   TABLES __SEQTA_TAB
    USING '1' __SCOPE __WAIT ' ' 'EZINTEGRACAO' _COLLECT.

ENDFUNCTION.
