FUNCTION ZDENQUEUE_INTEGRACAO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(ID_INTEGRACAO) TYPE  ZDE_ID_INTEGRACAO
*"     REFERENCE(_SCOPE) DEFAULT '3'
*"     REFERENCE(_SYNCHRON) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT ' '
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __SYNCHRON  TYPE DDENQSYNC.

  __SYNCHRON = _SYNCHRON.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_ZINTEGRACAO,
          MANDT	    TYPE SY-MANDT,
          ID_INTEGRACAO  TYPE ZDE_ID_INTEGRACAO,
        END OF %A_ZINTEGRACAO.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_ZINTEGRACAO.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_ZINTEGRACAO-MANDT.
  ENDIF.

  MOVE: ID_INTEGRACAO TO %A_ZINTEGRACAO-ID_INTEGRACAO.

* Preencher tab.bloqueio:

  __SEQTA_TAB-GNAME = 'ZINTEGRACAO'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG  = %A_ZINTEGRACAO.
  APPEND __SEQTA_TAB.

* Lock assigned:
  PERFORM SEND_ENQUEUE(SAPLSENA) TABLES __SEQTA_TAB USING '2' __SCOPE ' ' __SYNCHRON 'EZINTEGRACAO' _COLLECT.

ENDFUNCTION.
