FUNCTION ZENQUEUE_SOLICITACAO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(ID_SOLICITACAO) TYPE  ZDE_ID_SOLICITACAO
*"     REFERENCE(_SCOPE) DEFAULT '2'
*"     REFERENCE(_WAIT) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT SPACE
*"  EXCEPTIONS
*"      FOREIGN_LOCK
*"      SYSTEM_FAILURE
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __WAIT      TYPE DDENQWAIT.

  __WAIT = _WAIT.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_ZHCMT_PA_0011,
          MANDT          TYPE SY-MANDT,
          ID_SOLICITACAO TYPE ZDE_ID_SOLICITACAO,
        END OF %A_ZHCMT_PA_0011.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_ZHCMT_PA_0011.

  MOVE: ID_SOLICITACAO TO %A_ZHCMT_PA_0011-ID_SOLICITACAO.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_ZHCMT_PA_0011-MANDT.
  ENDIF.

* Preencher tab.bloqueio:
  __SEQTA_TAB-GNAME = 'ZHCMT_PA_0011'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG = %A_ZHCMT_PA_0011.
  APPEND __SEQTA_TAB.

* Fixar bloqueio:
  PERFORM SEND_ENQUEUE(SAPLSENA)
   TABLES __SEQTA_TAB
    USING '1' __SCOPE __WAIT ' ' 'EZHCMT_PA_0011' _COLLECT.

ENDFUNCTION.
