FUNCTION ZHCM_LOGIN_MOBILE.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_CPF) TYPE  STRING
*"     REFERENCE(I_ID_DISPOSITIVO) TYPE  STRING
*"     REFERENCE(I_PASSWORD) TYPE  STRING
*"  EXPORTING
*"     REFERENCE(E_TOKEN) TYPE  STRING
*"     REFERENCE(E_NOME) TYPE  STRING
*"  RAISING
*"      ZCX_SOL_MOBILE_RH
*"----------------------------------------------------------------------

  DATA(LC_SOL_MOBILE_RH) =
  ZCL_SOL_MOBILE_RH=>ZIF_SOL_MOBILE_RH~SET_LOGIN(
    EXPORTING
      I_CPF = I_CPF
      I_SENHA = I_PASSWORD
    IMPORTING
      E_TOKEN = E_TOKEN
      E_NOME  = E_NOME ).

  IF LC_SOL_MOBILE_RH IS NOT INITIAL.
    LC_SOL_MOBILE_RH->GET_ID_DISPOSITIVO(
      IMPORTING
        E_ID_DISPOSITIVO = DATA(E_ID_DISPOSITIVO)
    ).
  ENDIF.

  IF E_ID_DISPOSITIVO NE I_ID_DISPOSITIVO.

    CLEAR: E_TOKEN.

    RAISE EXCEPTION TYPE ZCX_SOL_MOBILE_RH
      EXPORTING
        TEXTID = VALUE #( MSGNO = ZCX_SOL_MOBILE_RH=>ZCX_DISPOSITIVO_NAO_AUTORIZADO-MSGNO MSGID = ZCX_SOL_MOBILE_RH=>ZCX_DISPOSITIVO_NAO_AUTORIZADO-MSGID )
        MSGTY  = 'E'
        MSGNO  = ZCX_SOL_MOBILE_RH=>ZCX_DISPOSITIVO_NAO_AUTORIZADO-MSGNO
        MSGID  = ZCX_SOL_MOBILE_RH=>ZCX_DISPOSITIVO_NAO_AUTORIZADO-MSGID.

  ENDIF.

ENDFUNCTION.
