FUNCTION ZHCM_RET_RERIODOS_FOLHA_PAG.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  EXPORTING
*"     REFERENCE(E_PERIODOS) TYPE  ZHCM_RET_PERIDOS_FOLHA_PDFS_T
*"----------------------------------------------------------------------

  DATA: LC_DATA_INICIAL	LIKE P0001-BEGDA,
        WA_PERIODOS     TYPE ZHCM_RET_PERIDOS_FOLHA_PDFS.

  CLEAR: E_PERIODOS.

  SELECT * INTO TABLE @DATA(IT_ZHCMT0004)
    FROM ZHCMT0004.

  SELECT * INTO TABLE @DATA(IT_PA0014)
    FROM ZHCMT_PA_0014
   WHERE CK_FOLHA_PAGAMENTO EQ @ABAP_TRUE.

  SORT IT_PA0014 DESCENDING BY ANOPR MESPR.

  SELECT SINGLE * INTO @DATA(WA_PA0013)
    FROM ZHCMT_PA_0013.

  SORT IT_ZHCMT0004 BY ANOPR MESPR.

  DO WA_PA0013-QTD_DIAS_FOLHA TIMES.

    READ TABLE IT_PA0014 INDEX SY-INDEX INTO DATA(WA_PA0014).
    IF SY-SUBRC IS NOT INITIAL.
      CONTINUE.
    ENDIF.

    READ TABLE IT_ZHCMT0004 WITH KEY ANOPR = WA_PA0014-ANOPR MESPR = WA_PA0014-MESPR INTO DATA(WA_ZHCMT0004) BINARY SEARCH.
    IF SY-SUBRC IS NOT INITIAL.
      CONTINUE.
    ENDIF.

    WA_PERIODOS-ANOPR = WA_ZHCMT0004-ANOPR.
    WA_PERIODOS-MESPR = WA_ZHCMT0004-MESPR.
    WA_PERIODOS-INIFP = WA_ZHCMT0004-INIFP.
    WA_PERIODOS-FIMFP = WA_ZHCMT0004-FIMFP.
    WRITE WA_ZHCMT0004-INIFP TO WA_PERIODOS-INIFP_FORMATADA.
    WRITE WA_ZHCMT0004-FIMFP TO WA_PERIODOS-FIMFP_FORMATADA.
    APPEND WA_PERIODOS TO E_PERIODOS.

  ENDDO.

ENDFUNCTION.
