FUNCTION ZDENQUEUE_SOLICITACAO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(ID_SOLICITACAO) TYPE  ZDE_ID_SOLICITACAO
*"     REFERENCE(_SCOPE) DEFAULT '3'
*"     REFERENCE(_SYNCHRON) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT ' '
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __SYNCHRON  TYPE DDENQSYNC.

  __SYNCHRON = _SYNCHRON.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_ZHCMT_PA_0011,
          MANDT	         TYPE SY-MANDT,
          ID_SOLICITACAO TYPE ZDE_ID_SOLICITACAO,
        END OF %A_ZHCMT_PA_0011.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_ZHCMT_PA_0011.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_ZHCMT_PA_0011-MANDT.
  ENDIF.

  MOVE: ID_SOLICITACAO TO %A_ZHCMT_PA_0011-ID_SOLICITACAO.

* Preencher tab.bloqueio:

  __SEQTA_TAB-GNAME = 'ZHCMT_PA_0011'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG  = %A_ZHCMT_PA_0011.
  APPEND __SEQTA_TAB.

* Lock assigned:
  PERFORM SEND_ENQUEUE(SAPLSENA) TABLES __SEQTA_TAB USING '2' __SCOPE ' ' __SYNCHRON 'EZHCMT_PA_0011' _COLLECT.

ENDFUNCTION.
