FUNCTION ZHCM_RET_RERIODOS_ESPELHO_PONT.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  EXPORTING
*"     REFERENCE(E_PERIODOS) TYPE  ZHCM_RET_PERIDOS_PONTO_PDFS_T
*"----------------------------------------------------------------------

  DATA: LC_DATA_INICIAL	LIKE P0001-BEGDA,
        WA_PERIODOS     TYPE ZHCM_RET_PERIDOS_PONTO_PDFS.

  CLEAR: E_PERIODOS.

  SELECT * INTO TABLE @DATA(IT_ZHCMT0004)
    FROM ZHCMT0004.

  SELECT * INTO TABLE @DATA(IT_PA0014)
    FROM ZHCMT_PA_0014
   WHERE CK_ESPELHO_PONTO EQ @ABAP_TRUE.

  SORT IT_PA0014 DESCENDING BY ANOPR MESPR.

  SELECT SINGLE * INTO @DATA(WA_PA0013)
    FROM ZHCMT_PA_0013.

  SORT IT_ZHCMT0004 BY ANOPR MESPR.

  DO WA_PA0013-QTD_DIAS_PONTO TIMES.

    READ TABLE IT_PA0014 INDEX SY-INDEX INTO DATA(WA_PA0014).
    IF SY-SUBRC IS NOT INITIAL.
      CONTINUE.
    ENDIF.

    READ TABLE IT_ZHCMT0004 WITH KEY ANOPR = WA_PA0014-ANOPR MESPR = WA_PA0014-MESPR INTO DATA(WA_ZHCMT0004) BINARY SEARCH.
    IF SY-SUBRC IS NOT INITIAL.
      CONTINUE.
    ENDIF.

    WA_PERIODOS-ANOPR = WA_ZHCMT0004-ANOPR.
    WA_PERIODOS-MESPR = WA_ZHCMT0004-MESPR.
    WA_PERIODOS-INITM = WA_ZHCMT0004-INITM.
    WA_PERIODOS-FIMTM = WA_ZHCMT0004-FIMTM.
    WRITE WA_ZHCMT0004-INITM TO WA_PERIODOS-INITM_FORMATADA.
    WRITE WA_ZHCMT0004-FIMTM TO WA_PERIODOS-FIMTM_FORMATADA.
    APPEND WA_PERIODOS TO E_PERIODOS.

  ENDDO.

ENDFUNCTION.
