FUNCTION ZHCM_RECUPERA_HASH_PDF.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_HASH) TYPE  STRING
*"  EXPORTING
*"     REFERENCE(E_PDF) TYPE  XSTRING
*"----------------------------------------------------------------------

  DATA: RG_SMARTFORM TYPE RANGE OF TDSFNAME,
        LN_SMARTFORM LIKE LINE OF RG_SMARTFORM.

  CHECK I_HASH IS NOT INITIAL.

  LN_SMARTFORM-SIGN   = 'I'.
  LN_SMARTFORM-OPTION = 'EQ'.
  LN_SMARTFORM-HIGH   = 'ZHCMS_PT0001'.
  LN_SMARTFORM-LOW    = 'ZHCMS_PT0001'.
  APPEND LN_SMARTFORM TO RG_SMARTFORM.

  LN_SMARTFORM-HIGH   = 'ZHCMS_PY0002'.
  LN_SMARTFORM-LOW    = 'ZHCMS_PY0002'.
  APPEND LN_SMARTFORM TO RG_SMARTFORM.

  SELECT SINGLE * INTO @DATA(WA_ZSMT0001)
    FROM ZSMT0001
   WHERE DS_AUTENTICACAO EQ @I_HASH
     AND NM_SMARTFORM    IN @RG_SMARTFORM.

  IF SY-SUBRC IS INITIAL.
    E_PDF = WA_ZSMT0001-RW_SMARTFORMS.
  ENDIF.

ENDFUNCTION.
