INTERFACE ZIF_INTEGRACAO_NEW_DOC_CTB
  PUBLIC .

  INTERFACES ZIF_INTEGRACAO_INJECT .

  DATA AT_ID_INTEGRACAO TYPE ZDE_ID_INTEGRACAO .
  DATA AT_DOC_CTB TYPE ZDE_NEW_DOC_CTB.
  DATA AT_ZFIT0158 TYPE ZFIT0158.
  DATA AT_BKPF TYPE BKPF.
  DATA AT_BSEG TYPE BSEG_T.
  DATA AT_RETORN TYPE ZDE_CNS_DOC_CTB_RET.

  CLASS-DATA AT_INTEGRACAO_NEW_DOC_CTB TYPE REF TO ZIF_INTEGRACAO_NEW_DOC_CTB.

  CLASS-METHODS GET_INSTANCE
    RETURNING
      VALUE(R_ZIF_INTEGRACAO_NEW_DOC_CTB) TYPE REF TO ZIF_INTEGRACAO_NEW_DOC_CTB
    RAISING
      ZCX_INTEGRACAO.

  METHODS SET_DS_DATA
    IMPORTING
      !I_INFO                             TYPE ZDE_INTEGRACAO_HTTP_CONFIG
    RETURNING
      VALUE(R_ZIF_INTEGRACAO_NEW_DOC_CTB) TYPE REF TO ZIF_INTEGRACAO_NEW_DOC_CTB
    RAISING
      ZCX_INTEGRACAO.

  METHODS GET_VALIDAR_DADOS
    RETURNING
      VALUE(R_ZIF_INTEGRACAO_NEW_DOC_CTB) TYPE REF TO ZIF_INTEGRACAO_NEW_DOC_CTB
    RAISING
      ZCX_INTEGRACAO.

  METHODS SET_SEND_MSG
    EXPORTING
      !E_MSG                              TYPE STRING
      !E_PROTOCOLO                        TYPE STRING
      !E_ZINTEGRACAO_LOG                  TYPE ZINTEGRACAO_LOG
    RETURNING
      VALUE(R_ZIF_INTEGRACAO_NEW_DOC_CTB) TYPE REF TO ZIF_INTEGRACAO_NEW_DOC_CTB
    RAISING
      ZCX_INTEGRACAO
      ZCX_ERROR .

  METHODS SET_NEW_DOC_CONTABIL
    IMPORTING
      !I_DADOS                            TYPE ZDE_NEW_DOC_CTB
    EXPORTING
      !E_DOCUMENTO                        TYPE BKPF
      !E_ERROS                            TYPE ZIB_CONTABIL_ERR_T
    RETURNING
      VALUE(R_ZIF_INTEGRACAO_NEW_DOC_CTB) TYPE REF TO ZIF_INTEGRACAO_NEW_DOC_CTB
    RAISING
      ZCX_INTEGRACAO
      ZCX_ERROR .

ENDINTERFACE.
