*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZPFE_CHVID_AGTOP.                 " Global Data
  INCLUDE LZPFE_CHVID_AGUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZPFE_CHVID_AGF00                       . " subprograms
  INCLUDE LZPFE_CHVID_AGI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZPFE_CHVID_AGF...                 " Subprograms
* INCLUDE LZPFE_CHVID_AGO...                 " PBO-Modules
* INCLUDE LZPFE_CHVID_AGI...                 " PAI-Modules
